sudo: required
dist: trusty

language: python

python:
  - "2.7"

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - oracle-java8-set-default
      - google-chrome-stable

env:
  global:
    - TRAVIS_NODE_VERSION="6"
    - JAVA_HOME="/usr/lib/jvm/java-8-oracle"
    - ES_HOST="localhost:9200"
    - ES_AWS="false"
    - ES_INDEX="searchable_items_blue"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/virtualenv/python2.7.9/lib/python2.7/site-packages
    - $TRAVIS_BUILD_DIR/scripts/elastic_search/tmp
    - node_modules

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - curl -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.1.2.zip && unzip elasticsearch-5.1.2.zip
  - ./elasticsearch-5.1.2/bin/elasticsearch -d
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install $TRAVIS_NODE_VERSION
  - make build
  - make run &

before_script:
  - sleep 5

script:
  - curl "http://localhost:9200"
  - make index
  - make tests

notifications:
  slack:
    secure: j510O1sCqnVN12VQ7GVW+uADxZaPp2cGvPDDVdqyVMIDPR6LlkFegAu/4cNJ907Eyo2ytMD/jYfNE4NmnqULDvyjzNDIYAltKxoDdUDGazIUK1hanMXuf5tDIzFyJX3NYB8V168EJnyjxUsbQ1N46DsG+AqJZLdW+tF63EMI8czmtuFa524cx6T+vt48vnrfJIcRupPllDmwQyiA3y2ufsRiYQ0ju+Yjn8p1e6LKikZk8lcdzpnwSKkcMYep1WUx9fRkUd5v7OwpggmCA4XeopkFLhuOmS7y6nzcy3R8gUB0P8Js7MQi2TKa0lkDkmSLshGHxXS2PqWD6EvgF638Kx2Wx1VYgtzruXJDWKznYHdmrbQGDu4B45bqvWTbz3+3JEEDQd4CQOQ3jTm6zeauMGn9S6vSM0pSJQk6OgQBGWFbsoCcwwboCiSbdcyGj4gao3zvYoDdoY5t3CXj+5xygbMCTYr3rbrQMig/BWonZSWtc58eGeXV82WK9sYAlnryomvrJ9F9NSzAnfp4CaPrWyyMyMlKpC7XOrENlndi/WvI9I8VvdcWtWnpsqLrwY5lN4hRurAn1H/qs+8tBZ6YfohxBgdZ4POJCZNZlsskQ4nnMFPTOlLKvta+VIDZd+XcuKs2ZaH8vL5nF6HW1rJp8qvsJ7HGtMW6wURP1Cu2u5M=
